### ISSUE TITLE
"Can't access Dropbox folder"

### ISSUE THREAD

**Issue by luni3359** [flathub/com.dropbox.Client#11]
Dropbox is not updating anything. It shows this message in the tray with another option asking to fix. If you click it then it asks for the system password but no matter how many times you put in the password it says "wrong password".

**Comment by wjt** [comment]
Try quitting Dropbox, then running from the command line:

```
flatpak run com.dropbox.Client
```

Is there any interesting output?

What is the `"path"` field in `~/.dropbox/info.json`?

**Comment by luni3359** [comment]
I'm afraid to say it just randomly started working again.
