### ISSUE TITLE
How can I sign in if I'm not shown a browser?

### ISSUE THREAD

**Issue by nmusatti** [flathub/com.dropbox.Client#202]
I just installed Dropbox on CentOS 8.3. If I start it I see several processes running:

    nick        8751    7623  0 19:35 tty2     00:00:00 bwrap --args 35 /app/bin/dropbox-app
    nick        8774    8751  0 19:35 tty2     00:00:00 bwrap --args 35 /app/bin/dropbox-app
    nick        8775    8774  0 19:35 tty2     00:00:00 /usr/bin/python3 /app/bin/dropbox-app
    nick        8780    8775  6 19:35 tty2     00:02:57 /app/extra/.dropbox-dist/dropbox-lnx.x86_64-112.4.321/dropbox

When I open Dropbox's menu it says `Starting...`; if I click on `Sign in` it changes to `Waiting to be linked to a Dropbox account...`, but nothing happens, the browser is not started and no login page appears. My default browser is Firefox and I have no problem opening my Dropbox account page from that. I tried looking around my system for a log file, but couldn't find it. There are some Dropbox related messages in the `/var/log/messages` file, but they don't shed any light on the situation, not to me at least. They all look like the following:

    Dec 30 19:36:00 imladris com.dropbox.Client.desktop[8751]: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-112.4.321/PyQt5.QtDBus.cpython-37m-x86_64-linux-gnu.so'

I noticed that about a second after this message there are a series of messages that appear to be related to a segmentation fault by the `xdg-desktop-portal` service, which end with:

    Dec 30 19:36:02 imladris systemd[7517]: xdg-desktop-portal.service: Main process exited, code=killed, status=11/SEGV

But I don't know if it's related to Dropbox or not. Does anybody have any idea on how I might recover from this situation? I remember that the non graphical version of Dropbox was supposed to print an URL that could be used to log into Dropbox, is there any way to recover that?

**Comment by wjt** [comment]
That segfault is probably very much related. xdg-desktop-portal is what handles the request from the Dropbox client to open a URL in a web browser.

**Comment by nmusatti** [comment]
The most evident problem appears to be this:

    [pipewire.c:118 open_plugin()] can't load /usr/lib64/spa-0.2/jack/libspa-jack.so: /usr/lib64/spa-0.2/jack/libspa-jack.so: cannot open shared object file: No such file or directory

I'm not sure whether this originates from the flatpak sandbox or from CentOS. I couldn't find any package providing libspa-jack.so in any of the repositories I'm using.
Note that I had an up to date flatpak installation running without problems under CentOS 7.9, until three days ago.

**Comment by nmusatti** [comment]
Actually the message above is only present the first time I start Dropbox after boot. The typical error message is:

    Jan  2 19:01:41 imladris dbus-daemon[3104]: [session uid=1001 pid=3104] Activating via systemd: service name='org.freedesktop.portal.Desktop' unit='xdg-desktop-portal.service' requested by ':1.177' (uid=1001 pid=319182 comm="/usr/libexec/flatpak-dbus-proxy --args=39 " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
    Jan  2 19:01:41 imladris systemd[3035]: Starting Portal service...
    Jan  2 19:01:41 imladris dbus-daemon[3104]: [session uid=1001 pid=3104] Successfully activated service 'org.freedesktop.portal.Desktop'
    Jan  2 19:01:41 imladris systemd[3035]: Started Portal service.
    Jan  2 19:01:41 imladris kernel: pool[319393]: segfault at 0 ip 00007fc9ddfbd9e4 sp 00007fc9ca3ce968 error 4 in libglib-2.0.so.0.5600.4[7fc9ddf81000+116000]
    Jan  2 19:01:41 imladris kernel: Code: 84 00 00 00 00 00 f3 0f 1e fa 48 83 ec 08 e8 b3 f1 fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 17 b8 05 15 00 00 84 d2 74 18 89 c1 48 83 c7 01 c1 e1 05 01
    Jan  2 19:01:41 imladris systemd[1]: Started Process Core Dump (PID 319400/UID 0).
    Jan  2 19:01:41 imladris systemd[3035]: xdg-desktop-portal.service: Main process exited, code=killed, status=11/SEGV
    Jan  2 19:01:41 imladris systemd[3035]: xdg-desktop-portal.service: Failed with result 'signal'.
    Jan  2 19:01:42 imladris systemd-coredump[319401]: Process 319390 (xdg-desktop-por) of user 1001 dumped core.#012#012Stack trace of thread 319393:#012#0  0x00007fc9ddfbd9e4 g_str_hash (libglib-2.0.so.0)#012#1  0x00007fc9ddfbce38 g_hash_table_lookup (libglib-2.0.so.0)#012#2  0x00007fc9de5e7f7e g_desktop_app_info_new (libgio-2.0.so.0)#012#3  0x000055d7f176c768 app_exists (xdg-desktop-portal)#012#4  0x000055d7f176deaf handle_open_in_thread_func (xdg-desktop-portal)#012#5  0x00007fc9de581377 g_task_thread_pool_thread (libgio-2.0.so.0)#012#6  0x00007fc9ddff7753 g_thread_pool_thread_proxy (libglib-2.0.so.0)#012#7  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#8  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#9  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319399:#012#0  0x00007fc9dd87d78d syscall (libc.so.6)#012#1  0x00007fc9de015ade g_cond_wait_until (libglib-2.0.so.0)#012#2  0x00007fc9ddfa1031 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)#012#3  0x00007fc9ddff7892 g_thread_pool_thread_proxy (libglib-2.0.so.0)#012#4  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#5  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#6  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319397:#012#0  0x00007fc9dd87d78d syscall (libc.so.6)#012#1  0x00007fc9de014fec g_mutex_lock_slowpath (libglib-2.0.so.0)#012#2  0x000055d7f17771d8 close_requests_in_thread_func (xdg-desktop-portal)#012#3  0x00007fc9de581377 g_task_thread_pool_thread (libgio-2.0.so.0)#012#4  0x00007fc9ddff7753 g_thread_pool_thread_proxy (libglib-2.0.so.0)#012#5  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#6  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#7  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319396:#012#0  0x00007fc9dd84efc8 __nanosleep (libc.so.6)#012#1  0x00007fc9dd84eece sleep (libc.so.6)#012#2  0x000055d7f1780cf3 background_monitor (xdg-desktop-portal)#012#3  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#4  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#5  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319390:#012#0  0x00007fc9dd877ca1 __poll (libc.so.6)#012#1  0x00007fc9ddfce9b6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)#012#2  0x00007fc9ddfced72 g_main_loop_run (libglib-2.0.so.0)#012#3  0x000055d7f1769f59 main (xdg-desktop-portal)#012#4  0x00007fc9dd7a97b3 __libc_start_main (libc.so.6)#012#5  0x000055d7f176a1de _start (xdg-desktop-portal)#012#012Stack trace of thread 319395:#012#0  0x00007fc9dd883257 epoll_wait (libc.so.6)#012#1  0x00007fc9c83f1985 impl_pollfd_wait (libspa-support.so)#012#2  0x00007fc9c83ef719 loop_iterate (libspa-support.so)#012#3  0x00007fc9deaddd86 do_loop (libpipewire-0.3.so.0)#012#4  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#5  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319391:#012#0  0x00007fc9dd877ca1 __poll (libc.so.6)#012#1  0x00007fc9ddfce9b6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)#012#2  0x00007fc9ddfceae0 g_main_context_iteration (libglib-2.0.so.0)#012#3  0x00007fc9ddfceb31 glib_worker_main (libglib-2.0.so.0)#012#4  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#5  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#6  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319392:#012#0  0x00007fc9dd877ca1 __poll (libc.so.6)#012#1  0x00007fc9ddfce9b6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)#012#2  0x00007fc9ddfced72 g_main_loop_run (libglib-2.0.so.0)#012#3  0x00007fc9de5c455a gdbus_shared_thread_func (libgio-2.0.so.0)#012#4  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#5  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#6  0x00007fc9dd882f23 __clone (libc.so.6)#012#012Stack trace of thread 319394:#012#0  0x00007fc9dd877ca1 __poll (libc.so.6)#012#1  0x00007fc9ddfce9b6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)#012#2  0x00007fc9ddfceae0 g_main_context_iteration (libglib-2.0.so.0)#012#3  0x00007fc9c8dffe6d dconf_gdbus_worker_thread (libdconfsettings.so)#012#4  0x00007fc9ddff6d4a g_thread_proxy (libglib-2.0.so.0)#012#5  0x00007fc9ddb5114a start_thread (libpthread.so.0)#012#6  0x00007fc9dd882f23 __clone (libc.so.6)
    Jan  2 19:01:42 imladris systemd[1]: systemd-coredump@2-319400-0.service: Succeeded.

**Comment by nmusatti** [comment]
This appears to be solved by v113.4.507
