### ISSUE TITLE
Dropbox folder doesn't show "updated checkmark"

### ISSUE THREAD

**Issue by ArtMiranda** [flathub/com.dropbox.Client#268]
On RPM Dropbox when the files are updated we can see in Nautilus a checkmark right next on the Dropbox directory and sub-directory

![image](https://user-images.githubusercontent.com/50926874/179638950-b7a85cf8-7406-4c77-bf8c-7c4bf953086b.png)
**_Not my desktop above_**

On flatpak Dropbox that icon isn't showed.

**Comment by wjt** [comment]
No, it's not resolved.

But: this can't be supported because Nautilus is running on the host, and this Flatpak cannot ship the Nautilus extension that shows those ticks.

**Comment by nvergottini** [comment]
> No, it's not resolved.
> 
> But: this can't be supported because Nautilus is running on the host, and this Flatpak cannot ship the Nautilus extension that shows those ticks.

Make sense. I appreciate the response.
