### ISSUE TITLE
Can't Sign In

### ISSUE THREAD

**Issue by mindinsomnia** [flathub/com.dropbox.Client#275]
Just tried using this today on my Steam Deck, and can't sign in.

The flatpak installed correctly by the appearance of it, the application launched, and it displayed an icon in the system tray, but clicking on the 'sign in' option from the system tray menu did nothing.

Tried a reboot, made no difference.

Tried running the application via the terminal to see if any error messages were produced.

It's a stock install of Steam OS on a Steam Deck, haven't made any modifications to the system.

**Comment by wjt** [comment]
I'm pretty sure that the 'sign in' option is meant to open up the login flow in the system web browser. With that in mind:

1. Do you have a web browser installed?
2. Can you run [Bustle](https://flathub.org/apps/details/org.freedesktop.Bustle), monitor the Session bus, then click Sign in from the menu and see what D-Bus messages are sent when you click it?

**Comment by mindinsomnia** [comment]
1. Yes, I had Firefox installed and setup as the default web browser.
2. Will try to do this right now and let you know the result.

**Comment by mindinsomnia** [comment]
Followed the steps above and saved the resulting log:
[2022-09-13 00:19:28.zip](https://github.com/flathub/com.dropbox.Client/files/9548925/2022-09-13.00.19.28.zip)

**Comment by wjt** [comment]
- Dropbox calls `org.freedesktop.portal.OpenURI.OpenURI('', 'https://www.dropbox.com/cli_link_nonce?nonce=[redacted]', @a{sv} {})`.
- The desktop portal calls `org.freedesktop.impl.portal.PermissionStore.Lookup('desktop-used-apps', 'x-scheme-handler/https')` and gets an error reply – but I think this is irrelevant.
- The portal then emits `org.gtk.gio.DesktopAppInfo.Launched(b'/var/lib/flatpak/exports/share/applications/org.mozilla.firefox.desktop', '', int64 6086, ['https://www.dropbox.com/cli_link_nonce?nonce=[redacted]'], {'origin-prgname': <b'/usr/lib/xdg-desktop-portal'>, 'origin-pid': <int64 1699>})`

So everything looks in order from the point of view of this app: it is correctly asking the portal to open a URI. It also looks like the portal believes it is launching Firefox with the correct URL.

**Comment by mindinsomnia** [comment]
Through more experimenting I discovered all flatpaks were impacted, and then more experimenting, it seems the issue is the latest beta version of Steam OS has an issue impacting URL opening of all Flatpaks. Switching from the Beta back to Stable resolved the issue.
