### ISSUE TITLE
Problem after the last update

### ISSUE THREAD

**Issue by speedytux** [flathub/com.dropbox.Client#282]
After the recent update of the flathub app 159.4.5870 it return the following error:

`$ flatpak run com.dropbox.Client

Traceback (most recent call last):
  File "/app/bin/dropbox-app", line 28, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
`

**Comment by Dskobra** [comment]
I'm also having this exact issue. Went to restart my computer after updates and boom dropbox didnt start and got that same error when trying to manually run it.

**Comment by nelas** [comment]
Same issue here. Could this commit be the cause 422635a11bfc0724c210e7944f659d61ee5bec6f?

**Comment by wjt** [comment]
Thanks for the report, I'm looking into it!

**Comment by wjt** [comment]
I bisected and it's actually caused by the GNOME runtime update. I don't understand why. I also am certain I tested that change... it's a mystery.

**Comment by wjt** [comment]
The fix should be live on Flathub in a few hours. If you are in dire need of Dropbox, the test build on #283 works again.

**Comment by nelas** [comment]
Thanks a lot @wjt!
