### ISSUE TITLE
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod

### ISSUE THREAD

**Issue by saulo1131** [flathub/com.dropbox.Client#291]
hi everyone. I have a problem in my debian 11. Can anyone help me please? Thank you very much. I am a beginner in linux, but i has already use ubuntu.
$ flatpak run com.dropbox.Client
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/cryptography.hazmat.bindings._openssl.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/cryptography.hazmat.bindings._padding.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/apex._apex.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/PyQt5.QtCore.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/PyQt5.QtGui.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/PyQt5.QtWidgets.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-163.4.5456/PyQt5.QtDBus.cpython-38-x86_64-linux-gnu.so'
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Nenhuma interface ?org.freedesktop.portal.OpenURI? no objeto no caminho /org/freedesktop/portal/desktop

**Comment by wjt** [comment]
> Nothing to do with Dropbox. You need to have xdg-desktop-portal, and [one of its backends](https://github.com/flatpak/xdg-desktop-portal/#using-portals), installed for Flatpak apps to work properly.
