### ISSUE TITLE
duplicate screenshots

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.dropbox.Client#4]
![captura de tela de 2018-07-03 11-41-13](https://user-images.githubusercontent.com/26097419/42226704-04c18932-7eb6-11e8-8de9-a48a0098c9c6.png)

**Comment by jgarciao** [comment]
I think this is related https://github.com/hughsie/appstream-glib/issues/244

**Comment by nedrichards** [comment]
Yes - it's the same issue.

**Comment by wjt** [comment]
"Resolved" in ee88c2641a7647772a81963399d57bc54ca2e8ee by virtue of only having English screenshots.
