### ISSUE TITLE
Wrong PID in ~/.dropbox/dropbox.pid

### ISSUE THREAD

**Issue by cvoltz** [flathub/com.dropbox.Client#43]
The PID in `~/.dropbox/dropbox.pid` for the Dropbox process is incorrect. 
`~/.dropbox/dropbox` does get written when the Dropbox client is started but it always seems to have the same value. As a result, none of the Dropbox CLI commands provided by [dropbox.py](https://www.dropbox.com/download?dl=packages/dropbox.py) work. For example, `dropbox status` always reports that Dropbox isn't running:

```
$ wget \
  --output-document dropbox \
  --quiet \
  'https://www.dropbox.com/download?dl=packages/dropbox.py'

$ chmod +x dropbox

$ ./dropbox status
Dropbox isn't running!

$ flatpak ps
Instance  PID    Application        Runtime
572743652 121495 com.dropbox.Client org.gnome.Platform

$ cat ~/.dropbox/dropbox.pid
7

$ flatpak info com.dropbox.Client/x86_64/stable
Ref: app/com.dropbox.Client/x86_64/stable
ID: com.dropbox.Client
Arch: x86_64
Branch: stable
Origin: com.dropbox.Client-origin
Collection ID: org.flathub.Stable
Date: 2019-08-01 08:57:09 +0000
Subject: update to 78.4.119 (754d478f)
Commit: 238b5b5f22319aa0ccb7e1500f16448d8063c9d32b082cc2d780481fd2f86c01
Parent: b9bbd3d01e483dd2f40b211797e16b63c2456e7c594a66cbb9b97d68f3b1b58a
Location: /var/lib/flatpak/app/com.dropbox.Client/x86_64/stable/238b5b5f22319aa0ccb7e1500f16448d8063c9d32b082cc2d780481fd2f86c01
Installed size: 1.5 MB
Runtime: org.gnome.Platform/x86_64/3.32
Sdk: org.gnome.Sdk/x86_64/3.32

$ lsb_release --description
Description:    CentOS Linux release 7.6.1810 (Core)
```

**Comment by cvoltz** [comment]
As a workaround, I created a [patch](https://gist.github.com/cvoltz/7198bddcf3d1f994cbd1bbec5d3db14a) for Dropbox's `dropbox.py` to get the right PID and it appears to work now.

Here is the patch:
```diff
--- dropbox.py
+++ dropbox.py
@@ -134,11 +134,12 @@
         FatalVisibleError("Platform not supported")

 def is_dropbox_running():
-    pidfile = os.path.expanduser("~/.dropbox/dropbox.pid")
-
     try:
-        with open(pidfile, "r") as f:
-            pid = int(f.read())
+        pid = subprocess.run("flatpak ps | awk '/dropbox/ { print $2 }'",
+                             shell=True, encoding="UTF-8",
+                             stdout=subprocess.PIPE)
+        pid = int(pid.stdout.strip())
+
         with open("/proc/%d/cmdline" % pid, "r") as f:
             cmdline = f.read().lower()
     except:
EOF
```
Here are the commands to get a patched copy of `dropbox.py` and make it available as the command `dropbox`:
```bash
wget \
  --output-document dropbox.py \
  --quiet \
  'https://www.dropbox.com/download?dl=packages/dropbox.py'

wget --quiet https://gist.githubusercontent.com/cvoltz/7198bddcf3d1f994cbd1bbec5d3db14a/raw/7e065eb5eb506a6f416e7e50fd938d3c69cd4e46/dropbox.patch

patch < dropbox.patch
chmod +x dropbox.py
mv dropbox.py ~/.local/bin/dropbox
```

**Comment by TingPing** [comment]
Inside of the sandbox it will never know the PID on the host. It is simply a broken design that doesn't work in a namespaced world.

**Comment by cvoltz** [comment]
Would it be possible to include the `dropbox.py` and have a method to run it in the same container as the Dropbox daemon? Then it could see the "correct" PID (from the standpoint of processes in the container).

**Comment by TingPing** [comment]
The PID in the container is always useless as it will be the same number every time (likely a low value like `2`).

Flatpak provides a unique instance-id in every running app (see `/.flatpak-info`) and that could be used for something I suppose.

Running `dropbox.py` outside of the sandbox your workaround is probably the best you can do.
