### ISSUE TITLE
Dropbox needs improvements...

### ISSUE THREAD

**Issue by calcatinge** [flathub/com.dropbox.Client#5]
I use CentOS 7 as a Workstation on all my laptops and desktops. The flatpak version installed is 0.8.8. I installed Dropbox on CentOS 7 from Flathub, but it lacks consistency compared to the one installed from dropbox.com. 

First of all, it stopped syncing my account after one day, leaving me with no other option than to remove and install it from the sources available on the website. The files synced already were not complete, as there still were some files left on the cloud and not synced to the workstation. 

Secondly, it does not provide a "systray" icon as the official one does with the TopIcons extension installed. This is leaving the user with no actual interaction with the app: you can not open preferences, log out, launch the website or edit options on your local install version. 

I really wanted to use this flatpak version and not the one available on the official website, but as it turned out, it was not a smart move at all. Why would you offer it if it does not provide the same experience as the original sources?

**Comment by nedrichards** [comment]
So, this is not the experience that I have of the application.

Could you install the latest flatpak from https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/ and try again? I believe that is significantly newer than the version in base CentOS 7 (and the one we run on the CentOS flathub servers)

**Comment by nmusatti** [comment]
@nedrichards, is Dropbox still working for you after the glibc/ext4 requirements began being enforced? Just to know whether it's still worthwhile to try out your suggestion. Thank you!

**Comment by jgarciao** [comment]
According to [this site](https://www.dropboxforum.com/t5/Error-messages/Dropbox-client-warns-me-that-it-ll-stop-syncing-in-Nov-why/td-p/306368) the ext4 filesystem requirement will be enforced on Nov. 7, 2018,

**Comment by gunwald** [comment]
> Secondly, it does not provide a "systray" icon as the official one does with the TopIcons extension installed. This is leaving the user with no actual interaction with the app: you can not open preferences, log out, launch the website or edit options on your local install version

I have the same issue. Although I have the Ubuntu AppIndicators extension up an running, I do not have a tray icon. So there is no feedback whether the app is active or not.

**Comment by wjt** [comment]
If you are able to, you could try to work on the outstanding issues on #17 to get AppIndicators working.

**Comment by wjt** [comment]
Next build should work with AppIndicators.
