### ISSUE TITLE
incorrect license?

### ISSUE THREAD

**Issue by cbm755** [flathub/com.dropbox.Client#6]
Gnome Software says "Free" and clicking on that says GPL-3.0+.  I think that is unlikely (although haven't carefully verified).

Probably this should be labelled "proprietary".

**Comment by nedrichards** [comment]
Ah, hrm, that's referring to the wrapper app, which is GPL-2.0+ so no matter what, this is just plain wrong. Thanks for reporting.

**Comment by ramcq** [comment]
Fixed! Sorry about that. Dodgy internal script at Endless (which I've also fixed) had GPL-3.0+ in it's template appdata.
