### ISSUE TITLE
libglapi.so dependency missing

### ISSUE THREAD

**Issue by mrambausek** [flathub/com.dropbox.Client#86]
I just encountered a dependency issue when installing the dropbox client on a pristine CentOS 7 system: 
`libglapi.so`
was not found. In that case, first of all, the error message was not really helpful (pointing to permission problems), but the output in the log (some txt) tells that in was not able to find this library.
It turns out, that from the gnome platform version 3.34 does not come with this lib, earlier versions do. However, the dropbox manifest by now only pulls in gnome runtime in 3.34. 
The fix in my case was to install in *addition* 
`org.freedesktop.Platform.GL.default`
. 

Could you please check, whether the dependencies indeed have to be updated?

**Comment by wjt** [comment]
What does `flatpak --version` report?

**Comment by mrambausek** [comment]
I currently don't have access to the machine where I experienced this issue, but the most recent official flatpak package for centos 7 has flatpak version 1.09, which admittedly is quite old. 
However, I have another CentOS machine in operation for quite some time (years) and for some reason there I did not have to manually install the GL runtime thing. Are these drivers supposed to be installed by the distribution or pulled in by some runtime? (Just would like to know whom to bother...)

**Comment by TingPing** [comment]
The runtime has a GL extension point that says to install if it matches the host. The `default` 'version' is a fake one that `flatpak` knows to install as a match if nothing else overrides it (like `nvidia`). Note that older runtimes did not package a `.default` driver.
