### ISSUE TITLE
Auto start dropbox flatpack

### ISSUE THREAD

**Issue by chui2ch** [flathub/com.dropbox.Client#9]
When I open the dropbox flatpak it opens my dropbox directory. Is there a way to start it with out that happening?

**Comment by krashekspres** [comment]
Having the same issue.

**Comment by krashekspres** [comment]
Created PR that adds --silent flag for starting client.
https://github.com/flathub/com.dropbox.Client/pull/12

**Comment by chui2ch** [comment]
> 
> 
> Created PR that adds --silent flag for starting client.
> #12

Will the tray icon still be available? Or does the --silent flag disable the icon?

**Comment by krashekspres** [comment]
it doesn't affect icon, it only disables running FE on start. Hmm might wanna use a different name for the flag?
