### ISSUE TITLE
Silent autostart on non Gnome desktops

### ISSUE THREAD

**Issue by danstewart** [flathub/com.dropbox.Client#93]
#13 doesn't work for non Gnome desktops.

As a workaround I've set this as my start up script:
```
#!/usr/bin/env bash

export DESKTOP_AUTOSTART_ID=1
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/dropbox-app com.dropbox.Client
```

**Comment by wjt** [comment]
Please try the test build on #96.

**Comment by danstewart** [comment]
Yeah that build works as expected - thanks

**Comment by wjt** [comment]
Merged that, should hit the repos in a few hours.
